language: c
compiler: gcc
before_script: meson --buildtype=debug travis
script: ninja -C travis test
sudo: required
dist: trusty

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "mMcLLwYU0rAQkJDQEw3NlX5l1e1DCuUfCHDhhvku4YMgLbMV3ADvrTvwfnZoimgRhVw5hWXLDGSdJ2jkwAraeNHLjyfDXn/NrPNvo8xAgbtlsWaCO76p3yecfdIzawbW2iKpkyIjw8fCgi2xRccvp2ZTinDspiN96aqqZuhwy/5WzavQG+ECTxkFW6tDcly/NUyy/CH6FH6fqp6tswd+VsqKgZLqybhrwW1/OPBr5e+QvVyfn3KAlWWiyUCj33WU1mxL+LhsS2cNXK5S5V1NOO624oXPCy6oJImONWh0feXuPu20LqoWE/uOVXOcNpSB+3EUA5mfj22ST0FPMrvwS9k2oZGLiIVfDyGmI+Hl/kI4tlh/7zolpaeQB/c8GCGRBuEr+k0J0pqVp7ptOSIw3n6l4R113Sp+EBqSOcNxNVgOoW6pMZSKM73Z9tlr1yHVKw0cfge8YUgplGf0cENgExyjW97W535h2VEMKlgdH9PCQgfTXYANBVp2My+u6CytUetjdJXLwjmjuXBiAtIsrSTUtZ3hx/D1RXygAq0l7YI4iHQOmumSy81rgO2xDs484z/Efs6EXg/zdxluPSND6o/A0OXx80FUa6dwDmP6AmBZsHggVUYK7Gduu0Dry/1lcc2avZqdyOSrLs02vnQaRxb84CKFbhUd93gnVlPki3M="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    packages:
    - python3-pip
    - pkg-config
    - libglib2.0-dev
    - gobject-introspection
    - libgirepository1.0-dev
    - libyaml-dev
    - unzip
    - curl
    - meson
    - ninja-build
    - gcc-6
    - gcc
    - gtk-doc-tools
    sources:
    - sourceline: 'deb http://us.archive.ubuntu.com/ubuntu/ zesty main universe'
    - sourceline: 'deb http://us.archive.ubuntu.com/ubuntu/ zesty-security main universe'
    - sourceline: 'deb http://us.archive.ubuntu.com/ubuntu/ zesty-updates main universe'

  coverity_scan:
    project:
      name: "sgallagher/libmodulemd"
      description: "Build submitted via Travis CI"
    notification_email: sgallagh@redhat.com
    build_command_prepend: "meson --buildtype=debug coverity"
    build_command:   "ninja -C coverity"
    branch_pattern: master
